apiVersion: apps/v1
kind: Deployment
metadata:
  name: databaes-landing-page
  namespace: databaes-landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: databaes-landing-page
  template:
    metadata:
      labels:
        app: databaes-landing-page
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: databaes-landing-page
          image: ghcr.io/tomasbferreira/databaes-landing-page:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: env-config
              mountPath: /usr/share/nginx/html/environment.json
              subPath: environment.json
            - name: env-config
              mountPath: /usr/share/nginx/html/topology.json
              subPath: topology.json
            - name: env-config
              mountPath: /usr/share/nginx/html/recent-activity.json
              subPath: recent-activity.json
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: env-config
          configMap:
            name: landing-page-env
