import { ServiceDef } from './models/service.model';

/**
 * IP convention:
 *   192.168.50.x    →  Proxmox management LAN (hypervisors + unmigrated services)
 *   192.168.10.x    →  VLAN 10 · production services (betsy)
 *   192.168.20.x    →  VLAN 20 · dev services (benedict)
 */
export const SERVICES: ServiceDef[] = [

  // ── Infrastructure (shared across envs) ─────────────────────────────────────
  {
    id: 'traefik',
    name: 'Traefik',
    description: 'Edge router, reverse proxy & Cloudflare tunnel termination',
    env: 'infra',
    url: 'https://traefik.databaes.net',
    healthUrl: 'https://traefik.databaes.net/ping',
    icon: '⇄',
    tags: ['proxy', 'ssl', 'cloudflare'],
  },
  {
    id: 'vault-prod',
    name: 'Vault (prod)',
    description: 'HashiCorp Vault HA — production secrets cluster (10.45 · 10.46)',
    env: 'infra',
    url: 'https://vault.databaes.net',
    healthUrl: 'https://vault.databaes.net/v1/sys/health',
    icon: '🔐',
    tags: ['ha', 'secrets', '1xx'],
  },
  {
    id: 'vault-dev',
    name: 'Vault (dev)',
    description: 'HashiCorp Vault HA — dev secrets cluster (20.45 · 20.46)',
    env: 'infra',
    url: 'https://vault-dev.databaes.net',
    healthUrl: 'https://vault-dev.databaes.net/v1/sys/health',
    icon: '🔐',
    tags: ['ha', 'secrets', '2xx'],
  },
  {
    id: 'authentik',
    name: 'Authentik',
    description: 'SSO identity provider, OIDC & LDAP — HA cluster (20.75 · 20.76)',
    env: 'infra',
    url: 'https://auth-dev.databaes.net',
    healthUrl: 'https://auth-dev.databaes.net/-/health/ready/',
    icon: '🪪',
    tags: ['ha', 'sso', 'oidc', '2xx'],
  },
  {
    id: 'rancher',
    name: 'Rancher',
    description: 'Kubernetes cluster management for k3s worker nodes (192.168.20.2)',
    env: 'infra',
    url: 'https://rancher-dev.databaes.net',
    healthUrl: 'https://rancher-dev.databaes.net/healthz',
    icon: '☸',
    tags: ['k8s', 'k3s', '2xx'],
  },
  {
    id: 'kuma',
    name: 'Uptime Kuma',
    description: 'Status & uptime monitoring for all services (192.168.20.2:3001)',
    env: 'infra',
    url: 'https://kumadev.databaes.net',
    healthUrl: 'https://kumadev.databaes.net',
    icon: '📊',
    tags: ['monitoring', '2xx'],
  },

  // ── Production (192.168.50.1xx) ──────────────────────────────────────────────
  {
    id: 'plex',
    name: 'Plex',
    description: 'Media server — movies, TV & music streaming (192.168.50.111:32400)',
    env: 'prod',
    url: 'https://plex.databaes.net',
    healthUrl: 'https://plex.databaes.net/identity',
    icon: '▶',
    tags: ['streaming', '1xx'],
  },
  {
    id: 'overseerr',
    name: 'Overseerr',
    description: 'Media request & discovery platform (192.168.50.111:5055)',
    env: 'prod',
    url: 'https://overseerr.databaes.net',
    healthUrl: 'https://overseerr.databaes.net/api/v1/status',
    icon: '🎬',
    tags: ['requests', '1xx'],
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    description: 'Self-hosted file storage & collaboration (192.168.50.105)',
    env: 'prod',
    url: 'https://cloud.databaes.net',
    healthUrl: 'https://cloud.databaes.net/status.php',
    icon: '☁',
    tags: ['storage', 'files', '1xx'],
  },
  {
    id: 'qbittorrent',
    name: 'qBittorrent',
    description: 'Torrent download client with web UI (192.168.10.65:8080)',
    env: 'prod',
    url: 'https://torrent.databaes.net',
    healthUrl: 'https://torrent.databaes.net',
    icon: '⬇',
    tags: ['download', '1xx'],
  },

  // ── QA / Test (test workloads on 192.168.50.111) ─────────────────────────────
  {
    id: 'jellyfin-test',
    name: 'Jellyfin',
    description: 'Open-source media server — test instance (192.168.50.111:8096)',
    env: 'qa',
    url: 'https://jellyfintest.databaes.net',
    healthUrl: 'https://jellyfintest.databaes.net/health',
    icon: '🎵',
    tags: ['streaming', 'test'],
  },
  {
    id: 'sonarr-qa',
    name: 'Sonarr',
    description: 'TV series manager — QA instance (192.168.50.111:8989)',
    env: 'qa',
    url: 'https://sonarrtest.databaes.net',
    healthUrl: 'https://sonarrtest.databaes.net/ping',
    icon: '📺',
    tags: ['tv', 'test'],
  },
  {
    id: 'radarr-qa',
    name: 'Radarr',
    description: 'Movie collection manager — QA instance (192.168.50.111:7878)',
    env: 'qa',
    url: 'https://radarrtest.databaes.net',
    healthUrl: 'https://radarrtest.databaes.net/ping',
    icon: '🎞',
    tags: ['movies', 'test'],
  },
  {
    id: 'prowlarr-qa',
    name: 'Prowlarr',
    description: 'Indexer manager — QA instance (192.168.50.111:9696)',
    env: 'qa',
    url: 'https://prowlarrtest.databaes.net',
    healthUrl: 'https://prowlarrtest.databaes.net/ping',
    icon: '🔍',
    tags: ['indexer', 'test'],
  },
  {
    id: 'overseerr-qa',
    name: 'Overseerr',
    description: 'Media requests — QA instance (192.168.50.111:5055)',
    env: 'qa',
    url: 'https://overseerrtest.databaes.net',
    healthUrl: 'https://overseerrtest.databaes.net/api/v1/status',
    icon: '🎬',
    tags: ['requests', 'test'],
  },
  {
    id: 'jackett-qa',
    name: 'Jackett',
    description: 'Torrent proxy & indexer — QA instance (192.168.50.111:9117)',
    env: 'qa',
    url: 'https://jacketttest.databaes.net',
    healthUrl: 'https://jacketttest.databaes.net',
    icon: '🔗',
    tags: ['indexer', 'test'],
  },
  {
    id: 'stremio-qa',
    name: 'Stremio',
    description: 'Streaming aggregator — QA instance (192.168.50.111:11470)',
    env: 'qa',
    url: 'https://stremiotest.databaes.net',
    healthUrl: 'https://stremiotest.databaes.net',
    icon: '📡',
    tags: ['streaming', 'test'],
  },

  // ── Dev (192.168.50.2xx mgmt · k3s dev worker VLAN 20 → 192.168.20.11) ───────
  {
    id: 'sonarr-dev',
    name: 'Sonarr',
    description: 'TV series manager — dev instance on k3s (192.168.20.11:8989)',
    env: 'dev',
    url: 'https://sonarr-dev.databaes.net',
    healthUrl: 'https://sonarr-dev.databaes.net/ping',
    icon: '📺',
    tags: ['tv', '2xx'],
  },
  {
    id: 'radarr-dev',
    name: 'Radarr',
    description: 'Movie collection manager — dev instance on k3s (192.168.20.11:7878)',
    env: 'dev',
    url: 'https://radarr-dev.databaes.net',
    healthUrl: 'https://radarr-dev.databaes.net/ping',
    icon: '🎞',
    tags: ['movies', '2xx'],
  },
  {
    id: 'prowlarr-dev',
    name: 'Prowlarr',
    description: 'Indexer manager — dev instance on k3s (192.168.20.11:9696)',
    env: 'dev',
    url: 'https://prowlarr-dev.databaes.net',
    healthUrl: 'https://prowlarr-dev.databaes.net/ping',
    icon: '🔍',
    tags: ['indexer', '2xx'],
  },
  {
    id: 'overseerr-dev',
    name: 'Overseerr',
    description: 'Media requests — dev instance on k3s (192.168.20.11:5055)',
    env: 'dev',
    url: 'https://overseerr-dev.databaes.net',
    healthUrl: 'https://overseerr-dev.databaes.net/api/v1/status',
    icon: '🎬',
    tags: ['requests', '2xx'],
  },
  {
    id: 'wikijs',
    name: 'Wiki.js',
    description: 'Internal knowledge base & documentation (192.168.20.11:3000)',
    env: 'dev',
    url: 'https://wikijs-dev.databaes.net',
    healthUrl: 'https://wikijs-dev.databaes.net',
    icon: '📖',
    tags: ['docs', '2xx'],
  },
];
