apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-uploads-pvc
  namespace: databaes-directus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
